print("Hello Amit! Python is working successfully in your jenkins") 
print("Hello Amit! i am update a code ") 
print("Hello Amit! i am added a auto pull function ")
print("Hello Amit! i am try to cross check ") 
print("Hello Amit! what are you doing  ") 
print("Hello Amit! ") 
print("Hello Amit! Python is working successfully in your jenkins") 
print("Hello Amit! how was learing of your devopes cource") 
